owner: briped
repo: uptime

sites:
  - name: P
    url: $URL_P
  - name: S
    url: $URL_S
  - name: R
    url: $URL_R

i18n:
  locale: da-DK
  #footer: This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org)
  footer: This page is powered by [Upptime](https://upptime.js.org)

status-website:
  cname: xmpl.dk
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  #introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /uptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
